import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Mist Fabric",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} flex flex-col min-h-screen antialiased`}
      >
        <Navbar />
        <hr className="border-gray-300" />

        <main className="grow w-3/4 mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
