import { Poppins } from "next/font/google";
import "../style/index.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToastProvider from "@/components/ToastProvider";
import { AppContextProvider } from "@/context/AppContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Mist Fabric",
  description: "An e-commerce store generated by next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} flex flex-col min-h-screen antialiased`}
      >
        <AppContextProvider>
          <Navbar />
          <hr className="border-gray-300" />
          <main className="grow w-3/4 mx-auto">{children}</main>
          <Footer />
        </AppContextProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
